server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/frod/native-file-repo
        git:
#          uri: file:///Users/sunwookim/Desktop/frod/git-local-repo
          uri: https://github.com/frod5/springcloudconfig


